version: '3'

services:
  bitbucket:
    image: atlassian/bitbucket-server:8.17  # Latest stable version as of 2025
    container_name: bitbucket
    ports:
      - "7990:7990"
      - "7999:7999"
    environment:
      - JDBC_DRIVER=org.postgresql.Driver
      - JDBC_URL=jdbc:postgresql://${DB_HOST}:5432/bitbucket
      - JDBC_USER=bitbucket
      - JDBC_PASSWORD=${DB_PASSWORD}
      - CATALINA_OPTS=-Dserver.port=7990 -Dserver.scheme=http -Dserver.secure=false -Dserver.context-path=/ -Dserver.proxy-port=7990
    volumes:
      - /opt/bitbucket/data:/var/atlassian/application-data/bitbucket
      - /opt/bitbucket/shared:/var/atlassian/application-data/bitbucket/shared
    restart: unless-stopped  # Added for reliability

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0  # Latest stable version as of 2025
    container_name: bitbucket-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - /opt/bitbucket/elasticsearch:/usr/share/elasticsearch/data
    restart: unless-stopped  # Added for reliability
